# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

@typing.final
class PyAction:
    @staticmethod
    def new_fold() -> PyAction: ...
    @staticmethod
    def new_raise(amount: builtins.int) -> PyAction: ...
    @staticmethod
    def new_check() -> PyAction: ...
    @staticmethod
    def new_call() -> PyAction: ...

@typing.final
class PyGame:
    def __new__(cls, settings: PySettings) -> PyGame: ...
    def play_turn(self, action: PyAction) -> None: ...
    def current_seat(self) -> builtins.int: ...

@typing.final
class PySettings:
    def __new__(cls, n_players: builtins.int, initial_stack: builtins.int) -> PySettings: ...

